#!/bin/bash
apt-get update -y
apt-get install -y apache2
systemctl start apache2
systemctl enable apache2
echo "<h1>Welcome to UniEvent System - GIKI</h1><p>Secure Backend Servers are Running!</p>" > /var/www/html/index.html
